const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);

export function nativeOnboardingPage(profileName: string, message: string, storeUrl: string, nonce: string): string {
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>连接系统 Chrome · ProfilePilot</title><style>
    :root{color-scheme:dark}*{box-sizing:border-box}body{font:15px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif;background:#1c1c1c;color:#ececec;margin:0}main{max-width:720px;margin:6vh auto;padding:32px}header{font-size:13px;color:#aaa}h1{font-size:28px;line-height:1.4;font-weight:600;margin:30px 0 12px}p,small{color:#bbb}ol{padding-left:24px}li{margin:14px 0}#status{padding:16px;background:#262626;border:1px solid #444;border-radius:8px;color:#eee}button,a{font:inherit}button,.button{display:inline-block;border:1px solid #555;border-radius:8px;background:#272727;color:#eee;padding:10px 16px;cursor:pointer;text-decoration:none}.primary{background:#ececec;color:#181818;border-color:#ececec}button:disabled{opacity:.55;cursor:wait}button:focus-visible,a:focus-visible{outline:2px solid #a9d8ca;outline-offset:4px}.actions{display:flex;gap:10px;flex-wrap:wrap}details{margin-top:24px;color:#aaa}summary{cursor:pointer}a{color:#ddd}small{display:block;margin-top:24px;font-size:12px}code{display:block;overflow-wrap:anywhere;padding:12px;background:#111;user-select:all}[hidden]{display:none!important}@media(max-width:540px){main{margin:2vh auto;padding:24px}h1{font-size:24px}}
    .directory{display:flex;align-items:flex-start;gap:12px;margin-top:8px;padding:12px;background:#111;border-radius:8px}.directory code{flex:1;min-width:0;padding:0}.directory button{flex:none;padding:6px 12px}#copy-status{margin:6px 0 0;font-size:13px}@media(max-width:540px){.directory{flex-direction:column}.directory button{align-self:flex-end}}
    </style></head><body><main><header>ProfilePilot / 浏览器连接</header><h1>连接 ${escape(profileName)}</h1><p>使用当前 Chrome 的页面和登录状态。首次安装一次，以后自动重连。</p><p id="status" role="status" aria-live="polite">${escape(message)}</p><section id="install">
    ${storeUrl ? `<p><a class="button primary" href="${escape(storeUrl)}" target="_blank" rel="noreferrer">从 Chrome Web Store 安装 ↗</a></p><p>商店版由 Chrome 自动更新。安装完成后返回此页连接。</p><details><summary>本地持久安装（开发版本）</summary>` : '<p>当前版本尚未上架商店。下面的本地安装会在 Chrome 重启后保留；只需选择一次文件夹。</p>'}
    <ol><li>打开扩展管理页，开启右上角“开发者模式”。</li><li>复制以下目录，点击“加载未打包的扩展程序”，在文件夹选择器中粘贴并选定。<div class="directory"><code id="path">正在准备扩展目录…</code><button id="copy" aria-describedby="copy-status" disabled>复制目录</button></div><p id="copy-status" role="status" aria-live="polite"></p></li><li>返回此页，点击“已安装，连接”。已有配对将自动恢复。</li></ol><div class="actions"><button class="primary" id="open-extensions" data-action="local-install">打开扩展管理页 ↗</button><button data-action="reveal-extension">显示文件夹</button></div>
    ${storeUrl ? '</details>' : ''}<p><button class="primary" id="refresh">已安装，连接</button></p><details><summary>更新或修复已安装的扩展</summary><p>应用启动时会校验并修复上述固定目录。更新应用后，空闲连接可自动重载扩展；若仍未连接，在扩展管理页点击 ProfilePilot 的“重新加载”，再返回此页。配对信息会保留。</p><p>若曾从旧目录加载，请重新选择上述固定目录。无需移除扩展或清除已有配对。</p></details>
    <details><summary>临时自动安装（仅本次 Chrome 会话）</summary><p>Chrome 149+ 支持调试安装。此方式在 Chrome 重启后可能被移除，适合临时试用。开启远程调试后，点击临时安装并允许 Chrome 的连接请求。</p><div class="actions"><button id="settings" data-action="open-debugging">打开 Chrome 调试设置 ↗</button><button id="retry" data-action="retry" hidden>临时安装或修复</button></div></details></section><p><button id="cancel" data-action="cancel">取消连接</button></p><small>连接请求五分钟有效。取消会停止本次连接，不会关闭 Chrome。</small></main><script nonce="${nonce}">
    const status=document.querySelector('#status');const copyButton=document.querySelector('#copy');const copyStatus=document.querySelector('#copy-status');const actionError=document.createElement('p');actionError.setAttribute('role','alert');actionError.hidden=true;status.after(actionError);let stopped=false;let extensionPath='';
    async function poll(){try{const r=await fetch(location.pathname+'/status');if(r.status===410){status.textContent='连接请求已过期，请返回 ProfilePilot 重新连接。';stopped=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);return}if(!r.ok)throw Error();const s=await r.json();status.textContent=s.message;if(s.extensionPath&&s.extensionPath!==extensionPath){extensionPath=s.extensionPath;document.querySelector('#path').textContent=extensionPath;copyButton.textContent='复制目录';copyStatus.textContent=''}copyButton.disabled=!extensionPath;document.querySelector('#retry').hidden=!['failed','cancelled','confirm-tab'].includes(s.stage);document.querySelector('#install').hidden=s.stage==='connected';document.querySelector('#cancel').hidden=['cancelled','connected'].includes(s.stage);if(s.stage==='connected')stopped=true}catch{status.textContent='无法连接 ProfilePilot。请确认应用仍在运行。'}finally{if(!stopped)setTimeout(poll,1000)}}
    document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{b.disabled=true;actionError.hidden=true;try{const r=await fetch(location.pathname+'/'+b.dataset.action,{method:'POST',headers:{'X-ProfilePilot-Onboarding':'1'}});if(!r.ok){const s=await r.json();throw Error(s.error||'请求未完成，请返回应用重新连接。')}}catch(e){actionError.textContent=e.message;actionError.hidden=false}finally{b.disabled=false}});
    copyButton.onclick=async()=>{if(!extensionPath)return;try{await navigator.clipboard.writeText(extensionPath);copyButton.textContent='已复制';const platform=navigator.userAgentData?.platform||navigator.platform||'';copyStatus.textContent=/mac/i.test(platform)?'目录已复制。在文件夹选择器中按 ⌘⇧G，粘贴路径后按 Return，再确认选择。':/win/i.test(platform)?'目录已复制。在文件夹选择器中按 Ctrl+L，粘贴路径后按 Enter，再点击“选择文件夹”。':'目录已复制。请在文件夹选择器中粘贴此路径并确认选择。'}catch{copyButton.textContent='复制目录';copyStatus.textContent='复制失败，请选中上方目录并手动复制。'}};document.querySelector('#refresh').onclick=()=>location.reload();poll();
    </script></body></html>`;
}
