export const IPC_CHANNELS = {
  getState: "profiles:get-state",
  createProfile: "profiles:create",
  renameProfile: "profiles:rename",
  launchProfile: "profiles:launch",
  launchProfileWithCdp: "profiles:launch-cdp",
  focusProfile: "profiles:focus",
  closeProfile: "profiles:close",
  openProfileFolder: "profiles:open-folder",
  deleteProfile: "profiles:delete",
  inspectAccountSyncDiff: "profiles:account:inspect-diff",
  scanProfileExtensions: "profiles:extensions:scan",
  inspectExtensionMigrationDiff: "profiles:extensions:inspect-diff",
  migrateExtensions: "profiles:extensions:migrate",
  deleteProfileExtension: "profiles:extensions:delete",
  syncAccount: "profiles:account:sync",
  cancelOperation: "profiles:operation:cancel",
  controlOperation: "profiles:operation:control",
  operationProgress: "profiles:operation-progress"
} as const;
