import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { ElectronDriver, delay, repoRoot, launchProfilePilotE2e } from './e2e/lib/electron-driver.mjs';

const require = createRequire(import.meta.url);
const fixture = await mkdtemp(path.join(os.tmpdir(), 'pp-phone-ui-'));
const socket = process.platform === 'win32' ? `\\\\.\\pipe\\pp-phone-ui-${process.pid}` : path.join(fixture, 'driver.sock');
const output = path.join(repoRoot, 'artifacts', 'phone-ui'); await mkdir(output, { recursive: true });
const child = spawn(require('electron'), [path.join(repoRoot, 'scripts/e2e/fixtures/phone-ui-main.cjs')], { cwd: repoRoot, windowsHide: true, env: { ...process.env, PHONE_UI_FIXTURE: fixture, PHONE_UI_SOCKET: socket }, stdio: ['ignore', 'pipe', 'pipe'] });
let logs = '', driver;
child.stdout.on('data', data => logs += data); child.stderr.on('data', data => logs += data);
try {
  for (let tries = 0; tries < 200; tries++) {
    if (child.exitCode !== null) throw new Error(`Phone UI fixture exited: ${logs}`);
    try {
      const connection = await new Promise((resolve, reject) => { const client = net.createConnection(socket); client.once('connect', () => resolve(client)); client.once('error', error => { client.destroy(); reject(error); }); });
      driver = new ElectronDriver(connection); break;
    } catch { await delay(50); }
  }
  assert.ok(driver, `Fixture driver did not start: ${logs}`);
  await driver.waitFor('h1', item => item.text === '手机控制');
  assert.equal((await driver.windows()).main.visible, false);
  assert.equal((await driver.query('[name="phoneDevice"] option')).count, 3);
  assert.equal((await driver.query('[data-action="connect"]')).count, 0, 'no separate connect button beside the device selector');
  assert.equal((await driver.query('[name="phoneDevice"] option[value^="connect:"]')).count, 0, 'selector contains physical devices only');
  assert.equal((await driver.query('.phone-route')).count, 2);
  assert.equal((await driver.query('.phone-readiness')).text, '连接条件已就绪');
  await driver.evaluate('document.querySelector("[data-phone-app-setup]").open=true');
  await driver.waitFor('.phone-preview img');
  const previewCalls = () => driver.evaluate('window.phoneFixture.previewCalls()');
  assert.equal(await previewCalls(), 1, 'connected USB phone automatically captures once');
  assert.equal((await driver.query('.phone-cli, #phone-start-form, [name="allowInput"], #phone-text-form')).count, 0);
  const state = () => driver.evaluate('window.phones.snapshot()');
  const phase = expected => driver.waitFor('.phone-task-heading', item => expected.test(item.text));
  const paint = () => driver.evaluate('document.querySelector(".phone-shell").scrollTo(0, 0); new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
  const idle = await state(); assert.equal(idle.devices[0].state.phase, 'stopped');
  assert.equal((await driver.query('.phone-setting-status[data-status="enabled"]')).count, 6);
  await delay(1200);
  await driver.evaluate('window.phoneFixture.setState("UI-TEST-1", { lastAction: "状态更新" })');
  assert.equal(await previewCalls(), 1, 'timer ticks and status updates retain the image without capturing again');
  await driver.domClick('[data-action="screenshot"]');
  await driver.waitFor('[data-action="screenshot"]', item => !item.disabled);
  assert.equal(await previewCalls(), 2, 'manual refresh remains available');
  assert.equal((await state()).devices[0].state.phase, 'stopped', 'one-off preview must release its view session');
  assert.equal((await driver.query('.phone-task-strip')).count, 0);
  await driver.domClick('[data-action="enlarge"]');
  await driver.waitFor('.phone-image-dialog[open]');
  await driver.domClick('.phone-image-dialog button');
  await driver.evaluate('window.phones.start("UI-TEST-1", "control", "Codex", "查看应用设置")');
  await phase(/Codex 正在操作/);
  assert.match((await driver.query('.phone-global-status')).text, /1 台手机/);
  await driver.domClick('[data-action="screenshot"]');
  assert.equal((await state()).devices[0].state.phase, 'controlling', 'preview must preserve the existing task');
  await paint();
  await writeFile(path.join(output, 'controlling.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  const active = (await state()).devices[0].state;
  await driver.evaluate('window.phoneFixture.setState("UI-TEST-1", { phase: "paused", generation: ' + (active.generation + 1) + ', lastAction: "手机已接管" })');
  await phase(/暂停/);
  assert.equal((await driver.query('[data-action="screenshot"]')).disabled, true);
  assert.match((await driver.query('.phone-connection')).text, /^已连接$/);
  await paint();
  await writeFile(path.join(output, 'paused.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domClick('[data-action="resume"]'); await phase(/Codex 正在操作/);
  await driver.domClick('[data-action="stop"]');
  await driver.waitFor('.phone-task-strip', item => !item.exists);
  await driver.evaluate('window.phoneFixture.setState("UI-TEST-1", { permissions: { overlay: true, notifications: true, accessibility: false }, readiness: { unlocked: true, computerConnected: true, usbConnected: true, wifiConnected: false, developerOptions: "enabled", usbDebugging: "enabled", wirelessDebugging: "enabled", accessibilityService: "disabled" } })');
  await driver.waitFor('[data-setting-open="accessibility"]');
  assert.equal((await driver.query('[data-action="screenshot"]')).disabled, true);
  await paint();
  await writeFile(path.join(output, 'permission-missing.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domClick('[data-setting-open="accessibility"]');
  await driver.waitFor('#phone-message', item => /已在手机打开设置/.test(item.text));
  await driver.evaluate('window.phoneFixture.setState("UI-TEST-1", { permissions: { overlay: true, notifications: true, accessibility: true }, readiness: { unlocked: true, computerConnected: true, usbConnected: true, wifiConnected: false, developerOptions: "enabled", usbDebugging: "enabled", wirelessDebugging: "enabled", accessibilityService: "running" } })');
  await driver.domClick('[data-phone-options] summary');
  await driver.domClick('[data-action="rename"]');
  await driver.domInput('.phone-name-dialog input', '<手机 & 名称>');
  await driver.domClick('.phone-name-dialog button[type="submit"]');
  await driver.waitFor('[name="phoneDevice"] option:checked', item => item.text === '<手机 & 名称>');
  assert.equal(await driver.evaluate('document.documentElement.scrollWidth > innerWidth'), false);
  await driver.domClick('[data-phone-options] [data-action="emulator"]');
  await driver.waitFor('.phone-emulator-dialog[open]');
  await driver.domClick('.phone-emulator-dialog [data-close]');
  assert.equal((await driver.query('[name="phoneDevice"]')).value, 'UI-TEST-1');
  await driver.domClick('[data-phone-options] [data-action="wifi"]');
  await driver.waitFor('.phone-wireless-dialog[open]');
  await driver.waitFor('.wireless-error', item => /尚未发现/.test(item.text));
  await driver.domClick('[data-first-pair]');
  await paint();
  await writeFile(path.join(output, 'wireless-guide.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domClick('[data-next]');
  await driver.waitFor('[data-candidate="0"]');
  await driver.domClick('[data-candidate="0"]');
  assert.equal((await driver.query('[name="pairAddress"]')).value, '192.168.1.8:37123');
  await driver.domInput('[name="pairCode"]', '654321');
  await driver.evaluate(`window.phoneFixture.setState('UI-TEST-2', { lastAction: '同步不应清除配对表单' })`);
  assert.equal((await driver.query('[name="pairCode"]')).value, '654321');
  await driver.domClick('[data-pair-form] button[type="submit"]');
  await driver.waitFor('.wireless-error', item => /未确认配对成功/.test(item.text));
  assert.equal((await driver.query('[name="pairCode"]')).value, '');
  await driver.domInput('[name="pairCode"]', '123456');
  await driver.domClick('[data-pair-form] button[type="submit"]');
  await driver.waitFor('[data-connect-form]');
  assert.equal((await driver.query('[name="pairCode"]')).exists, false);
  await driver.waitFor('[data-candidate="0"]');
  await driver.domClick('[data-candidate="0"]');
  assert.equal((await driver.query('[name="connectAddress"]')).value, '192.168.1.8:40235');
  await paint();
  await writeFile(path.join(output, 'wireless-connect.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domInput('[name="connectAddress"]', '192.168.1.8:37123');
  await driver.domClick('[data-connect-form] button[type="submit"]');
  await driver.waitFor('.wireless-error', item => /未建立无线连接/.test(item.text));
  await driver.domInput('[name="connectAddress"]', '192.168.1.8:40235');
  await driver.domClick('[data-connect-form] button[type="submit"]');
  await driver.waitFor('[data-prepare]');
  const wireless = (await state()).devices.find(d => d.id === '192.168.1.8:40235');
  assert.equal(wireless.state, null, 'pairing/connecting must not start control or install the app');
  await driver.domClick('[data-finish]');
  await driver.waitFor('[name="phoneDevice"] option:checked', item => item.text === 'Wireless Test Phone');
  await driver.domClick('[data-phone-options] [data-action="wifi"]');
  await driver.waitFor('.wireless-error', item => /尚未发现|确认设备身份/.test(item.text));
  await driver.domClick('[data-manual]');
  await driver.waitFor('[data-connect-form]');
  await driver.domClick('.phone-wireless-dialog [data-close]');
  assert.equal((await driver.query('.phone-wireless-dialog')).exists, false);
  // Same physical phone across USB/Wi-Fi: one selector option and live status.
  await driver.domInput('[name="phoneDevice"]', 'UI-TEST-1');
  await driver.evaluate('window.phoneFixture.setConnection(true)');
  assert.equal((await state()).devices.length, 5);
  assert.equal((await driver.query('[name="phoneDevice"] option')).count, 4);
  assert.equal((await driver.query('[name="phoneDevice"] option:checked')).text, '<手机 & 名称>');
  await driver.evaluate('window.phones.start("UI-TEST-1", "control", "Codex", "检查应用设置")');
  await phase(/正在操作/);
  await driver.evaluate('window.phoneFixture.setConnection(true)');
  assert.match((await driver.query('.phone-global-status')).text, /1 台手机/);
  await driver.evaluate('window.phoneFixture.setConnection(false)');
  await driver.waitFor('[name="phoneDevice"]', item => item.value === '192.168.1.9:40236');
  assert.equal((await driver.query('[data-route="usb"]')).count, 1, 'USB shares the same device card even when Wi-Fi is connected');
  assert.equal((await driver.query('[data-route="wifi"] .phone-route-badge')).text, '已连接');
  assert.match((await driver.query('.phone-connection-note')).text, /Wi-Fi/);
  assert.equal((await driver.query('.phone-error')).exists, false);
  await driver.waitFor('.phone-preview img');
  await driver.waitFor('[data-action="screenshot"]', item => !item.disabled);
  assert.equal((await state()).devices.find(device => device.id === '192.168.1.9:40236').state.phase, 'controlling', 'automatic Wi-Fi preview preserves the active task');
  await paint();
  await writeFile(path.join(output, 'same-phone-wifi.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domClick('[data-action="pause"]'); await phase(/暂停/);
  assert.equal((await driver.query('[data-action="resume"]')).count, 1);
  assert.equal((await driver.query('[data-action="screenshot"]')).disabled, true);
  await driver.domClick('[data-action="stop"]');
  await driver.evaluate('window.phoneFixture.setOffline()');
  await driver.waitFor('.phone-connection', item => /未连接/.test(item.text));
  assert.equal((await driver.query('.phone-setting-status[data-status="enabled"]')).count, 0);
  assert.equal((await driver.query('.phone-setting-status[data-status="unknown"]')).count, 6);
  assert.equal((await driver.query('.phone-preview img')).count, 0);
  assert.equal((await driver.query('.phone-readiness')).text, '待确认');
  await driver.domClick('[data-route="usb"] [data-action="usb"]');
  await driver.waitFor('.phone-usb-dialog[open]');
  assert.match((await driver.query('[data-usb-help]')).text, /Windows.*macOS/s);
  await writeFile(path.join(output, 'usb-guide.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domClick('.phone-usb-dialog header [data-close]');
  assert.equal((await driver.query('.phone-usb-dialog')).exists, false);
  await paint();
  await writeFile(path.join(output, 'offline.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  // Opening the homepage discovers the selected tablet without opening a wizard
  // or establishing a debugging/control connection.
  const connectionCalls = () => driver.evaluate('window.phoneBasicFixture.calls().then(calls => calls.filter(args => ["connect", "pair"].includes(args[0])).length)');
  const beforeDiscovery = await connectionCalls();
  await driver.evaluate('window.phoneDiscoveryFixture.set("adb-UI-TEST-1-xyz _adb-tls-connect._tcp 192.168.1.9:40236")');
  await driver.domInput('[name="phoneDevice"]', 'emulator-5554');
  await driver.domInput('[name="phoneDevice"]', 'UI-TEST-1');
  await driver.waitFor('[data-route="wifi"] .phone-route-badge', item => item.text === '已发现 · 待连接');
  assert.equal((await driver.query('[data-route="wifi"]')).attributes['data-debug-connected'], 'false');
  assert.equal((await driver.query('[data-action="basic-control"]')).disabled, true);
  assert.equal((await driver.query('.phone-wireless-dialog')).exists, false);
  await paint();
  await writeFile(path.join(output, 'wireless-discovered.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domInput('[name="phoneDevice"]', 'UI-TEST-2');
  await driver.waitFor('[data-route="wifi"] .phone-route-badge', item => item.text === '已开启 · 待连接');
  await driver.evaluate('window.phoneDiscoveryFixture.set("adb-UI-TEST-1-xyz _adb-tls-connect._tcp 192.168.1.9:40236", false)');
  await driver.domInput('[name="phoneDevice"]', 'UI-TEST-1');
  await driver.waitFor('[data-route="wifi"] .phone-route-badge', item => item.text === '发现但不可达');
  assert.equal(await connectionCalls(), beforeDiscovery, 'background discovery never connects or pairs');
  await driver.evaluate('window.phoneDiscoveryFixture.set(null)');
  console.log('Homepage wireless discovery: selected device only, no control connection, unreachable endpoint and fresh switch state passed.');
  await driver.domInput('[name="phoneDevice"]', 'emulator-5554');
  await driver.waitFor('.phone-connection', item => /未连接/.test(item.text));
  assert.equal((await driver.query('[name="phoneDevice"] option:checked')).text, 'Android 模拟器');
  assert.equal((await driver.query('.phone-setting')).count, 3, 'App permissions stay visible for an emulator');
  assert.match((await driver.query('.phone-emulator-connection [data-action="emulator"]')).text, /启动.*模拟器/);
  assert.doesNotMatch((await driver.query('.phone-connection-note')).text, /请用 USB|手机上允许/);
  await paint();
  await writeFile(path.join(output, 'emulator-offline.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domClick('.phone-emulator-connection [data-action="emulator"]');
  await driver.waitFor('.phone-emulator-dialog[open]');
  assert.equal((await driver.query('.phone-connect-dialog:not(.phone-emulator-dialog)[open]')).count, 0);
  await driver.waitFor('[data-emulator-name="Fixture_AVD"]');
  await driver.domClick('[data-emulator-name="Fixture_AVD"]');
  await driver.waitFor('.phone-connection', item => /^已连接$/.test(item.text), { timeoutMs: 15000 });
  await driver.waitFor('.phone-emulator-dialog', item => !item.exists);
  assert.equal((await driver.query('.phone-setting')).count, 3, 'only app permissions apply to emulator');
  assert.equal((await driver.query('[data-setting="usbDebugging"], [data-setting="wirelessDebugging"]')).count, 0);
  await driver.evaluate('window.phoneFixture.setState("emulator-5554", { permissions: { overlay: false, notifications: true, accessibility: true } })');
  await driver.waitFor('[data-setting-open="overlay"]');
  await driver.domClick('[data-setting-open="overlay"]');
  await driver.waitFor('#phone-message', item => /模拟器窗口内/.test(item.text));
  assert.equal((await driver.query('[data-action="screenshot"]')).disabled, true);
  await paint();
  await writeFile(path.join(output, 'emulator-permissions.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  assert.equal(await driver.evaluate('document.documentElement.scrollWidth > innerWidth'), false);
  await driver.evaluate('window.phoneFixture.setCloud(0)');
  await driver.domInput('[name="phoneDevice"]', 'cloud-ui-test');
  await driver.waitFor('.phone-connection', item => /未连接/.test(item.text));
  assert.equal((await driver.query('[data-action="screenshot"]')).disabled, true);
  assert.equal((await driver.query('.phone-setting-status[data-status="enabled"]')).count, 3);
  assert.match((await driver.query('[data-setting="usbDebugging"]')).text, /待确认/);
  await paint();
  await writeFile(path.join(output, 'cloud-online.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.evaluate('window.phoneFixture.setCloud(0, { debugReasons: { wirelessDebugging: "denied" }, appVersion: "0.2.1" })');
  await driver.waitFor('[data-setting="wirelessDebugging"]', item => /系统拒绝读取/.test(item.text));
  assert.match((await driver.query('[data-setting="wirelessDebugging"]')).text, /没有读取此开关的权限/);
  await driver.evaluate('window.phoneFixture.setCloud(0, { developerOptions: "enabled", usbDebugging: "enabled", wirelessDebugging: "disabled", debugReasons: { wirelessDebugging: "system-value" } })');
  await driver.waitFor('[data-route="wifi"] .phone-route-badge', item => item.text === '未连接');
  assert.match((await driver.query('[data-setting="wirelessDebugging"]')).text, /未开启/);
  assert.equal((await driver.query('.phone-readiness')).text, '连接条件已就绪');
  await driver.evaluate('window.phoneFixture.setCloud(0, { developerOptions: "enabled", usbDebugging: "disabled", wirelessDebugging: "enabled" })');
  await driver.waitFor('.phone-readiness', item => item.text === '连接条件已就绪');
  assert.equal((await driver.query('.phone-connection')).text, '未连接');
  assert.equal((await driver.query('[data-route="usb"] .phone-route-badge')).text, '未连接');
  assert.equal((await driver.query('[data-action="screenshot"]')).disabled, true);
  await driver.domClick('[data-phone-options] summary');
  await paint();
  await writeFile(path.join(output, 'approved-design-live-layout.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.evaluate('window.phoneFixture.setCloud(60000)');
  await driver.waitFor('.phone-connection', item => /未连接/.test(item.text));
  assert.equal((await driver.query('.phone-setting-status[data-status="enabled"]')).count, 0);
  assert.match((await driver.query('.phone-updated')).text, /最后上报/);
  await driver.domClick('[data-phone-options] summary');
  await driver.domClick('[data-phone-options] [data-action="cloud-link"]');
  await driver.waitFor('.phone-connect-dialog[open] [data-create]');
  await driver.domClick('[data-create]');
  await driver.waitFor('[data-result] textarea');
  assert.match((await driver.query('[data-result] textarea')).value, /^profilepilot:\/\/status/);
  assert.equal(await driver.evaluate('document.querySelector("[data-result] textarea").readOnly'), true);
  await driver.domClick('.phone-connect-dialog[open] [data-close]');
  // Reconnection in an inactive workspace waits until it is shown. A failed
  // capture does not repeatedly create sessions or spam the phone with retries.
  await driver.evaluate('window.workspacePane = { active: false }; document.dispatchEvent(new Event("workspace-visibilitychange"))');
  const beforeReconnect = await previewCalls();
  await driver.evaluate('window.phoneFixture.setConnection(true)');
  await driver.domInput('[name="phoneDevice"]', 'UI-TEST-1');
  await delay(1200);
  assert.equal(await previewCalls(), beforeReconnect, 'inactive workspace does not capture');
  await driver.evaluate('window.phoneFixture.previewBehavior({ fail: true })');
  await driver.evaluate('window.workspacePane.active = true; document.dispatchEvent(new Event("workspace-visibilitychange"))');
  await driver.waitFor('[data-action="screenshot"]', item => item.text === '重试');
  await delay(1200);
  await driver.evaluate('window.phoneFixture.setState("UI-TEST-1", { lastAction: "截图失败后更新状态" })');
  assert.equal(await previewCalls(), beforeReconnect + 1, 'failed automatic preview is not retried by polling');
  await driver.domClick('[data-action="screenshot"]');
  await driver.waitFor('.phone-preview img');
  assert.equal(await previewCalls(), beforeReconnect + 2, 'manual retry recovers the preview');
  await driver.evaluate('window.workspacePane.active = false; document.dispatchEvent(new Event("workspace-visibilitychange")); window.workspacePane.active = true; document.dispatchEvent(new Event("workspace-visibilitychange"))');
  assert.equal(await previewCalls(), beforeReconnect + 2, 'returning to a pane keeps the cached image');
  // Delay an old phone response until after selection changes; it must never
  // populate the newly selected phone's preview, even if its capture fails.
  await driver.evaluate('window.phoneFixture.previewBehavior({ delay: 1200 })');
  await driver.domClick('[data-action="screenshot"]');
  await driver.waitFor('[data-action="screenshot"]', item => item.text === '获取中…');
  await driver.evaluate('window.phoneFixture.previewBehavior({ fail: true })');
  await driver.domInput('[name="phoneDevice"]', 'UI-TEST-2');
  await driver.waitFor('[data-action="screenshot"]', item => item.text === '重试');
  assert.equal((await driver.query('.phone-preview img')).exists, false, 'late screenshot from the previous device is discarded');
  await driver.domClick('[data-action="screenshot"]');
  await driver.waitFor('.phone-preview img');
  // A phone waiting for user readiness gets its first image only after unlock.
  await driver.evaluate('window.phoneFixture.setOffline()');
  await driver.domInput('[name="phoneDevice"]', 'UI-TEST-1');
  const readiness = (await state()).devices.find(device => device.id === 'UI-TEST-1').state.readiness;
  await driver.evaluate(`window.phoneFixture.setState("UI-TEST-1", { readiness: ${JSON.stringify({ ...readiness, unlocked: false })} })`);
  const beforeUnlock = await previewCalls();
  await driver.evaluate('window.phoneFixture.setConnection(true)');
  await driver.waitFor('.phone-screen-bar', item => /请先解锁/.test(item.text));
  assert.equal(await previewCalls(), beforeUnlock);
  await driver.evaluate(`window.phoneFixture.setState("UI-TEST-1", { readiness: ${JSON.stringify({ ...readiness, unlocked: true })} })`);
  await driver.waitFor('.phone-preview img');
  assert.equal(await previewCalls(), beforeUnlock + 1, 'unlock after reconnection automatically displays the phone');
  await driver.evaluate(`window.phoneFixture.setState("UI-TEST-1", { readiness: ${JSON.stringify({ ...readiness, unlocked: false })} })`);
  assert.equal((await driver.query('.phone-connection-help')).exists, false, 'screen lock alone does not mean connection failure');
  await driver.evaluate('window.phoneFixture.setConnection(false)');
  await driver.evaluate('window.phoneFixture.setUnresponsive("UI-TEST-1", true)');
  await driver.waitFor('.phone-connection-help');
  assert.equal((await driver.query('.phone-connection')).text, 'App 未响应');
  assert.equal((await driver.query('.phone-readiness')).text, '暂时无法读取');
  assert.equal((await driver.query('[data-route="wifi"] .phone-route-badge')).attributes['data-tone'], 'ready', 'App failure does not hide a working debug connection');
  assert.match((await driver.query('.phone-updated')).text, /最后上报/);
  assert.equal((await driver.query('.phone-setting-status[data-status="unknown"]')).count, 6);
  assert.equal((await driver.query('.phone-error')).exists, false, 'raw transport failure is replaced by recovery guidance');
  assert.match((await driver.query('.phone-connection-help')).text, /仍能识别.*权限和画面都无法更新.*上次.*尚未确认.*解锁.*ProfilePilot.*同一网络/s);
  assert.equal((await driver.query('[data-action="install-phone-app"]')).text, '重新连接手机 App');
  assert.equal((await driver.query('[data-action="basic-control"]')).disabled, false, 'basic control stays available without a responsive App');
  assert.equal((await driver.query('.phone-error-details')).attributes.open, undefined);
  assert.match((await driver.query('.phone-status-note')).text, /不代表权限已关闭/);
  await paint();
  await writeFile(path.join(output, 'companion-unresponsive.png'), Buffer.from((await driver.screenshot()).pngBase64, 'base64'));
  await driver.domClick('.phone-error-details summary');
  await driver.evaluate('window.phoneFixture.setUnresponsive("UI-TEST-1", true)');
  assert.equal(await driver.evaluate('document.querySelector(".phone-error-details").open'), true, 'status updates retain expanded diagnostics');
  await driver.evaluate('window.phoneFixture.setUnresponsive("UI-TEST-1", false)');
  await driver.waitFor('.phone-connection-help', item => !item.exists);
  assert.equal((await driver.query('.phone-connection')).text, '已连接');
  assert.equal((await driver.query('.phone-setting-status[data-status="enabled"]')).count, 6);
  assert.equal((await driver.query('[data-action="screenshot"]')).disabled, true, 'recovered connection does not bypass the lock');
  console.log('Connection recovery guidance: screen lock versus timeout, unknown permissions, reconnect instructions and automatic recovery passed.');
  console.log('Automatic preview: USB/Wi-Fi, cached image, background deferral, manual retry, stale response and unlock passed.');
  console.log('Cloud UI: live diagnostics without a control connection, unavailable debugging switches and stale status passed.');
  console.log('Emulator UI: startup/connection, no USB wizard, post-connection permissions and emulator-specific guidance passed.');
  console.log(JSON.stringify({ ok: true, fixture: 'isolated mock devices; no ADB', checks: ['device-only selector', 'one route sufficient', 'automatic preview without polling', 'six live settings', 'manual refresh and retry', 'existing task preserved', 'pause and resume', 'permission setup entry', 'escaped rename', 'no CLI or session form', 'wireless pairing', 'USB/Wi-Fi deduplication', 'offline clears stale permissions and screen', 'hidden workspace deferral', 'late response discarded', 'unlock enables automatic preview'], screenshots: output }, null, 2));

} finally {
  if (driver) { await driver.request('quit', {}, 1000).catch(() => {}); driver.close(); }
  for (let attempts = 0; attempts < 50 && child.exitCode === null; attempts++) await delay(100);
  if (child.exitCode === null) child.kill();
  child.stdout.destroy(); child.stderr.destroy();
  if (path.dirname(path.resolve(fixture)) !== path.resolve(os.tmpdir()) || !path.basename(fixture).startsWith('pp-phone-ui-')) throw new Error('Refusing to clean a directory outside the test fixture.');
  await rm(fixture, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 });
}

// Real app + real preload, with smoke mode disabling device polling.
const realApp = await launchProfilePilotE2e({ mode: 'background', env: { CPM_START_VIEW: 'phones' } });
try {
  assert.deepEqual((await realApp.driver.evaluate('window.phones.snapshot()')).devices, []);
  await realApp.driver.waitFor('.phone-empty');
  assert.equal((await realApp.driver.query('[data-action="connect"]')).count, 0);
  assert.equal((await realApp.driver.query('[name="phoneDevice"]')).value, '');
  await realApp.driver.domClick('.phone-connection-section [data-action="usb"]');
  await realApp.driver.waitFor('.phone-usb-dialog[open]');
  await realApp.driver.domClick('.phone-usb-dialog footer [data-close]');
  assert.equal((await realApp.driver.query('[name="phoneDevice"]')).value, '', 'no phantom device after cancelling the first connection');
  await realApp.driver.domClick('[data-phone-options] summary');
  await realApp.driver.domClick('[data-action="mobile"]');
  await realApp.driver.waitFor('.mobile-dialog[open]');
  await realApp.driver.domClick('[data-mobile="close"]');
  assert.equal((await realApp.driver.query('[data-workspace="phones"][aria-current="page"]')).exists, true);
  await realApp.driver.domClick('[data-workspace="browser"]');
  await realApp.driver.waitFor('[data-workspace="browser"][aria-current="page"]');
  assert.deepEqual((await realApp.driver.evaluate('window.phones.snapshot()')).devices, []);
  await assert.rejects(realApp.driver.evaluate(`window.phones.start('UI-TEST-1', 'control', 'fixture', 'must reject')`), /手机工作区/);
  await assert.rejects(realApp.driver.evaluate(`window.phones.pairWireless('192.168.1.8:37123', '123456')`), /手机工作区/);
  console.log('Real application phone workspace, preload, navigation and IPC boundary: passed (device polling disabled).');
} finally { await realApp.stop(); }
