import type { BrowserTask, TaskAttachment, TaskSettings, TaskStream } from "../shared/tasks";
import { TERMINAL_TASKS, hasTaskBrowser } from "../shared/tasks";
import { taskIcon as icon } from "./task-icons";
import { renderExecutionStatus, renderAgentProgress } from "./task-progress";
import { previewMarkup } from "./task-preview";
import { escapeTaskHtml as e, taskMarkdown } from "./task-rich-text";
import { draftKey, MessageDrafts } from "./task-interaction-model";

export interface WorkbenchOptions { drafts: MessageDrafts; attachments: TaskAttachment[]; settings: TaskSettings; hint: string; status: string; inspector: boolean; stream?: TaskStream; replyError?: string; }
function attachments(key: string, options: WorkbenchOptions): string {
  const selected = options.drafts.get(key).attachments;
  return `<div class="chosen-files">${selected.map(id => `<span class="file-chip">${e(options.attachments.find(file => file.id === id)?.name || id)}<button type="button" data-message-remove="${e(id)}" data-draft-key="${e(key)}" aria-label="移除附件">×</button></span>`).join("")}</div><button type="button" data-action="attach-message" data-draft-key="${e(key)}" title="添加本轮附件">${icon("plus")} 添加附件</button>`;
}
function decisionForm(task: BrowserTask, options: WorkbenchOptions): string {
  const decision = task.pending; if (!decision) return "";
  const key = draftKey(task.id, "reply-task", decision.id);
  return `<section class="task-decision-card" aria-label="需要你处理"><form id="reply-task" class="decision task-composer" data-task-id="${e(task.id)}" data-decision-id="${e(decision.id)}" data-decision-kind="${decision.kind}" data-draft-key="${e(key)}"><div class="eyebrow">${decision.kind === "confirmation" ? "等待确认" : decision.kind === "handoff" ? "浏览器由你操作" : "等待回答"}</div><h2>${e(decision.title)}</h2><div class="task-markdown">${taskMarkdown(decision.details)}</div><label for="answer">回答或补充说明</label><textarea name="answer" id="answer" ${decision.kind === "question" ? "required" : ""} data-autogrow data-editor-key="${e(key)}" aria-describedby="reply-help">${e(options.drafts.get(key).text)}</textarea><div class="compose-toolbar">${attachments(key, options)}${decision.kind === "confirmation" && decision.permissionScope ? `<label>授权范围<select name="permissionScope"><option value="once">仅这次操作</option><option value="session">本会话同范围操作</option></select></label><p class="muted">${e(decision.permissionScope.label)} · ${e(decision.permissionScope.scope)}</p>` : ""}</div><p id="reply-help" class="muted">${decision.kind === "confirmation" ? "请使用明确的确认或拒绝按钮；输入中的 Enter 只换行。" : e(options.hint)}</p>${options.replyError ? `<p role="alert" class="field-error">${e(options.replyError)}</p>` : ""}<div class="actions">${decision.kind === "handoff" ? '<button type="button" data-action="focus-browser">打开浏览器处理</button>' : ""}<button type="submit" class="primary" name="decision" value="approve">${decision.kind === "confirmation" ? "确认这次操作" : "发送并继续"}</button>${decision.kind === "confirmation" ? '<button type="submit" name="decision" value="reject">不执行，重新处理</button>' : ""}</div></form></section>`;
}
export function taskQuickControls(task: BrowserTask): string {
  if (TERMINAL_TASKS.has(task.status)) return "";
  const control = (action: string, label: string) => `<button type="button" data-control="${action}" id="task-control-${action}">${label}</button>`;
  return `<div class="task-quick-controls" role="group" aria-label="任务控制">${["running", "queued"].includes(task.status) ? control("pause", "暂停") : !task.pending ? control("resume", "继续任务") : ""}${control("cancel", "停止任务")}</div>`;
}
function sessionSettings(task: BrowserTask, settings: TaskSettings): string {
  return `<dialog id="task-session-settings" class="task-session-settings" aria-labelledby="task-session-title">
    <header><h2 id="task-session-title">会话设置</h2><button type="button" data-action="close-session-settings" aria-label="关闭会话设置">${icon("close")}</button></header>
    <div class="session-profile">${icon("browser")}<span>${e(task.profileName)}</span></div>
    <form id="task-model-form" data-task-id="${e(task.id)}"><label for="session-model">后续使用的模型</label><div class="session-model-row"><input id="session-model" name="model" required value="${e(task.model || settings.model)}"><button type="submit">保存模型</button></div></form>
    <form id="task-limits-form" data-task-id="${e(task.id)}"><h3>累计运行上限</h3><div class="session-limits">${(["minutes", "actions", "budgetUsd"] as const).map(name => `<label>${({ minutes: "分钟", actions: "动作次数", budgetUsd: "费用 USD" })[name]}<input type="number" name="${name}" min="${name === "budgetUsd" ? ".01" : "1"}" step="${name === "budgetUsd" ? ".01" : "1"}" required value="${task.limits[name]}"></label>`).join("")}</div><button type="submit">更新上限</button></form>
    <section><h3>会话授权</h3>${(task.permissionRules || []).map(rule => `<p>${e(rule.label)} · ${e(rule.scope)}<button type="button" data-revoke-permission="${e(rule.id)}">撤销</button></p>`).join("") || '<p class="muted">没有会话授权规则。</p>'}</section>
  </dialog>`;
}
export function workbenchThread(task: BrowserTask, options: WorkbenchOptions): string {
  const active = !TERMINAL_TASKS.has(task.status);
  const compact = !active && !task.pending && !task.messageQueue?.length;
  const takeover = active ? `<button type="button" class="browser-takeover" data-control="takeover" id="task-control-takeover" ${hasTaskBrowser(task) ? "" : 'disabled aria-describedby="task-takeover-reason"'}>立即停止 · 我来操作</button>${!hasTaskBrowser(task) ? '<small id="task-takeover-reason">任务连接浏览器后可接管</small>' : ""}` : "";
  const queue = task.messageQueue || [];
  const queueView = queue.length ? `<section class="task-message-queue" aria-label="待发送消息"><h2>下一轮 · ${queue.length} 条</h2>${queue.map(message => `<article id="queued-${e(message.id)}"><p>${e(message.message)}</p><small>${message.attachmentIds.length} 个附件</small><button type="button" data-edit-queued="${e(message.id)}">取回编辑</button><button type="button" data-remove-queued="${e(message.id)}">撤回</button></article>`).join("")}</section>` : "";
  const pending = task.pending ? `<div class="task-pending-summary task-decision-summary" role="status"><strong>${e(task.pending.title)}</strong><button type="button" data-action="focus-reply">前往回答</button></div>` : "";
  return `<div class="task-thread-status">${pending}${task.needsReconciliation ? '<p class="history-reconcile">继续执行前需要核查上次操作结果。</p>' : ""}</div>${task.archivedAt ? `<div class="task-archive-notice">已归档 · 记录保留<button type="button" data-restore-task="${e(task.id)}">移出归档</button></div>` : ""}<div class="task-detail ${options.inspector ? "" : "inspector-collapsed"} ${compact ? "is-terminal" : ""}"><div class="thread-main">${decisionForm(task, options)}${renderExecutionStatus(task)}${renderAgentProgress(task)}<section class="thread-transcript" aria-label="对话"><div class="event-list" id="events"><div id="task-chat" class="task-chat-surface" data-task-chat-owned></div>${task.items.length ? `<section class="history-items"><div class="panel-header"><h2>逐项结果</h2>${!active && task.items.some(item => item.status !== "completed") ? '<button type="button" data-action="retry-items">继续所选项</button>' : ""}</div>${task.items.map(item => `<div class="item" id="item-${e(item.id)}">${!active && item.status !== "completed" ? `<input type="checkbox" name="retryItem" value="${e(item.id)}" aria-label="继续 ${e(item.label)}">` : ""}<span class="pill">${e(({ pending: "待处理", running: "处理中", waiting_user: "待补充", completed: "完成", skipped: "跳过", failed: "失败", uncertain: "结果未确认" })[item.status])}</span><div>${e(item.label)}<div class="task-markdown">${taskMarkdown(item.result || "")}${taskMarkdown(item.evidence || "")}</div></div></div>`).join("")}</section>` : ""}${(task.outputs?.length || task.attachments.length) ? `<section class="history-files" aria-label="任务产物">${[...(task.outputs || []), ...task.attachments].map(file => `<span><button type="button" data-preview-artifact="${e(file.id)}">${icon("paperclip")}${e(file.name)} · 预览</button><button type="button" data-output-file="${e(file.id)}">打开原文件</button></span>`).join("")}</section>` : ""}</div></section><button type="button" class="scroll-latest task-jump-latest" data-action="jump-latest" hidden>回到最新消息</button><footer class="history-footer">${queueView}<div id="task-chat-composer" class="task-chat-surface" data-task-chat-owned></div></footer><div id="task-thread-end" class="task-thread-end" aria-hidden="true"></div></div><aside id="task-inspector" class="thread-inspector" aria-label="当前浏览器" ${options.inspector ? "" : "hidden"}><button type="button" class="close-browser-panel" data-action="toggle-task-inspector" aria-label="关闭浏览器面板" title="关闭浏览器面板">${icon("close")}</button>${previewMarkup()}<div class="browser-context-identity">${icon("browser")}<strong>${e(task.profileName)}</strong></div>${takeover}</aside></div>${sessionSettings(task, options.settings)}`;
}
